### ISSUE TITLE
第25节，如图，{authUser}这样的写法是指authUser是一个属性吗？

### ISSUE THREAD

**Issue by yangfan1992** [xugy0926/learn-webapp-guideline#54]
ru't如图
![image](https://user-images.githubusercontent.com/24215571/33378137-db736e26-d54e-11e7-9f3b-3a2925d6dcd1.png)
![image](https://user-images.githubusercontent.com/24215571/33378216-138b7e0c-d54f-11e7-8ce2-4db4ab3887d6.png)

**Comment by xugy0926** [comment]
是的。module.exports 导出的是一个json对象。

假如 module.exports = authUser，那么你可以按照下面方式写。

```js
var authUser = require('../middlewares/auth');

app.use(authUser);
```
